### ISSUE TITLE
Invalid Url each time. 

### ISSUE THREAD

**Issue by hirokoyama75** [zekesarosi/hpa_menu_package#1]
#Today's date doesn't seem to work even with response code 200. 
Tried menu.collect_week("2023-09-12"), menu.collect_week("2023-9-12"), and multiple other dates with no avail.
I tried requesting the data on my own end and getting back "'str' object has no attribute 'json'"
Tried reading through the response but comes back with stuff unrelated with food, however comes with light connection to nutrislice.

**Comment by zekesarosi** [comment]
obviously the api that this package calls has been deprecated by nutrislice. If I have time I'll investigate how menu data is collected by the online menu.

**Comment by zekesarosi** [comment]
the issue has been resolved, if you want to test yourself feel free.

**Comment by hirokoyama75** [comment]
I went in and checked which websites and apis nutrislice calls to, and found the new updated api link that works if you want. Found it this morning sorry; but your old code will probably work if you replace the link.

**Comment by zekesarosi** [comment]
> I went in and checked which websites and apis nutrislice calls to, and found the new updated api link that works if you want. Found it this morning sorry; but your old code will probably work if you replace the link.

the issue has been resolved
